version: '3'

services:
  game-server:
    image: llmctf/2025q-web-smolder_alexandria
    privileged: true
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io
    ports:
      - 3700:3700

networks:
  ctfnet:
    external: true