version: '3'

services:
  game-server:
    image: llmctf/2025q-web-orion_override
    privileged: true
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io
    ports:
      - 3555:3000

networks:
  ctfnet:
    external: true